version: '3.8'
services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - WS_PATH=/ws
      - STUN_URLS=stun:stun.l.google.com:19302,stun:global.stun.twilio.com:3478
      - DISABLE_LIMIT=true
      - RESULT_PERSIST=false
      - CORS_ORIGINS=http://localhost:5173,http://127.0.0.1:5173
